### PR TITLE
Feature/apstrike/add rw async functions

### PR DESCRIPTION
**Pull request by apstrike**
Proposed change to the register model to add asynchronous read/write functions to the generated register model. 
This is a feature that I believe would be useful for testing SystemRDL address maps implemented in RTL (such as with the PeakRDL-regblock exported). 
The async read/write ability would allow a user to create async read/write callback functions that could perform reads/writes to an RTL simulation using (for example) the CocoTB framework.

### CODE REVIEW

**Comment by apstrike** [comment]
@krcb197 I agree that this may be a more advanced usage of the register model one that I would think to be very useful to users who are validating any RTL. 
CocoTB is a fairly popular coroutine based cosimulation library for writing RTL testbenches in Python & this tool would I think be really useful for anyone defining address maps with systemRDL and writing testbenches using CocoTB. It has some predefined bus classes for common bus interfaces such as the AXI4Lite protocol to interact with an RTL simulation. These functions have asynchronous read/write functions for a user to access the simulated RTL. The reason I wanted to add these functions to the API is to give a user a clean way of using these buses (or any other interface they might make with CocoTB) and I could not find a way to use asynchronous functions within a non-asynchronous callback function. Hence I added the asynchronous functions and their corresponding callbacks. 

To answer your questions a little more explicitly:
1. Does this need to be implemented within the API itself, or could this be implemented in the call-back layer, possibly with some instructions/examples in the documentation?
   - Unfortunately, I could not find a way to do this without defining asynchronous callbacks
 2.  Could this be a build switch such that the async extensions only appear if requested?
   - Yes I would be glad to add this in

I'll also work on adding testcases.

If this is a feature you'd rather not be added to the project, or have a better way to implement the feature, please let me know.

**Comment by krcb197** [comment]
@apstrike,

Thank you for those answers, 

Do you think anyone would ever want both the normal version and the async version of the functions? 

If the answer to the question above is no, then we can address most of my concerns about complexity for users as they will only see one version which changes depending on the boolean build parameter. I think we can have two versions of the library (build on the same base classes to avoid duplication) one with async callback and one as it is today. That would remove the need for the `async_` prefix on the function names (short is always good). The Jinja code between the two would be minimised to the 

I would be happy to see this feature in the library, it will be a great opportunity for me to extend my own knowledge of the async parts of python which I don't use often. 

Does that seem reasonable?

**Comment by apstrike** [comment]
yes I agree with you. I don't see it likely that a user would want to perform both regular and asynchronous accesses to the register model.

And to make sure I understand, by two versions of the library, are you thinking of having the switch determine if the read/write API's are prefixed with `async`?

**Comment by krcb197** [comment]
> 
> And to make sure I understand, by two versions of the library, are you thinking of having the switch determine if the read/write API's are prefixed with `async`?

I think the libraries might need to be a bit different, I would prefer to avoid having an entirely duplicated library but the callbacks do currently end up almost everywhere. Maybe these should be a Union of the Aync and non-async versions. 

I think we need a parameter on the export method, that propagates up to peakrdl too and down into the Jinja templates that controls which version is generated.

**Comment by krcb197** [comment]
@apstrike 

I am planning a fairly significant restructure in order to break up the output files, see #73 and #76. The motivation for this is that even for a modest design the size of the generated code can be 10MB+ and the auto generated unit tests can be 100MB+. This restructuring could create a merge nightmare for anyone who has been developing separately. Can you let me know if you are looking at the we discussed in the earlier in this thread, I am happy to wait until these changes have been integrated to make your life easier.

**Comment by apstrike** [comment]
@krcb197 I have been working on these changes, however it will probably take me about a week until I can get the PR updated. So if you'd like to work on #73 and #76, go ahead and worst case I will update this branch with those changes and deal with whatever problems come up.

**Comment by krcb197** [comment]
If you have already started, I will hold off and let you finish. Please reach out if you want any help or would like to agree any aspects of the approach.

**Comment by apstrike** [comment]
@krcb197 I think the changes I've made is what were looking for. an `--async` command line switch has been added to enable the use of async read/write access functions. I tried to minimize the amount of code I needed to copy but had some trouble with the registers & the context manager in the end. The unittests have also been updated to accommodate for async read/write access. One thing to note is that the Python 3.7 unittest TestCase class doesn't really work well with async functions and so I needed to use the `asynctest` library for the unit tests. From what I understand, it's just an extension of the `unittest` library that also supports calling asynchronous `MockObjects`.

**Comment by krcb197** [comment]
@apstrike 

Thank you again for this submission.

I have had a quick look this evening, I will have a more detailed. Two comments that immediately came to mind:
1) Can you include a bit of documentation to explain this feature, this could either be a subsection in the existing part of the documentation about callbacks. This may only need to a few sentences.
2) Regarding python 3.7, I am aware some users are using Python 3.7 and it not yet end of life. I am OK that a feature is only available in later versions but I would rather not break the package for users of Python 3.7. Is it possible to put a conditional statement such that the async option is only available in 3.8 and later?

Keith

**Comment by krcb197** [comment]
I have discovered that you can put version specific dependencies in setup.py, see: https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#platform-specific-dependencies

**Comment by krcb197** [comment]
I have merged this to a development branch so that I can make a few updates and do some testing for myself.

**Comment by jahagirdar** [comment]
@krcb197 , 
Do you have an example code for using this PR with Cocotb?

**Comment by jahagirdar** [comment]
Sure, I will try to create a basic test environment this weekend

**Comment by jahagirdar** [comment]
[cocotb.tar.gz](https://github.com/krcb197/PeakRDL-python/files/13931459/cocotb.tar.gz)

Added a targz file. containing a sample cocotb code to read and write to registers .

**Comment by jahagirdar** [comment]
The previous upload requires a commercial simulator.
I have commented out the backdoor access logic to make it work with the opensource verilator simulator. in this tarball
[cocotb_verilator.tar.gz](https://github.com/krcb197/PeakRDL-python/files/13931517/cocotb_verilator.tar.gz)

**Comment by krcb197** [comment]
@jahagirdar

There would be two steps to using peakrdl-python with this:

1. build a Python Register Abstraction Layer from the systemRDL. Once peakrdl-python has been installed (along with system rdl compiler), this can be done as follows (The `--async` is very important to ensure the async variant of the package gets built): 
```bash
peakrdl python chip_with_registers.rdl -o . --async
```
2. integrate the generated package into the test with the callbacks and replace the address based read and write operations with operations to the register model. I have modified the `test.py` script in the targx file to show this:
```python
import cocotb
from cocotbext.axi import AxiLiteMaster, AxiBus
from cocotb.clock import Clock
from cocotb.triggers import Timer, FallingEdge

from chip_with_registers.reg_model.chip_with_registers import chip_with_registers_cls
from chip_with_registers.lib import AsyncCallbackSet


@cocotb.test()
async def test(dut):
    dut.val.value =0xff
    cocotb.start_soon(Clock(dut.clk, 1, "ns").start())
    cocotb.start_soon(reset(dut))
    axi = AxiLiteMaster(AxiBus.from_prefix(
        dut, 's_axil'), dut.clk, dut.arst_n, False
    )

    # set up the register model, the callbacks must match the protocol defined by
    async def read_callback(addr: int, width: int, accesswidth: int) -> int:
        """
        32-bit read operation to the register model
        """
        return await int.from_bytes(axi.read(addr, 4), byteorder='big', signed=False)

    async def write_callback(addr: int, width: int, accesswidth: int, data: int) -> None:
        """
        32-bit write operation to the register model
        """
        await axi.write(addr, data.to_bytes(length=4, byteorder='big', signed=False))

    dut_reg_model = chip_with_registers_cls(callbacks = AsyncCallbackSet(read_callback=read_callback,
                                                                         write_callback=write_callback))

    # test as before

    await Timer(20, 'ns')
    ############## Output Enable Reg ##############
    await dut_reg_model.GPIO_OE.gpio_oe.write(0x367)
    # Backdoor check
    await FallingEdge(dut.clk)
    # cocotb.log.info(dut.hwif_out.__dict__)
    # assert dut.hwif_out.GPIO_OE.gpio_oe.value == 0x367, "GPIO_OE Backdoor Mismatch"
    # Frontdoor check
    rdata = await dut_reg_model.GPIO_OE.gpio_oe.read() # field read
    assert rdata.data == b'g\x03\x00\x00', "GPIO_OE frontdoor failed"
    ############## Input Reg ##############
    # dut.hwif_in.GPIO_I.gpio_i.next = 0x1aa
    dut.val.value = 0x1aa
    await FallingEdge(dut.clk)

    rdata = await dut_reg_model.GPIO_I.read() # register read
    assert rdata.data == b'\xaa\x01\x00\x00', "GPI backdoor read failed"


async def reset(dut):
    dut.arst_n.value = 0
    await Timer(10, 'ns')
    dut.arst_n.value = 1

```

I did not have a simulator or verilator installed so I have not been able to test this code, however, I hope it is good enough to explain the principles.

There are some points to note:
- using the register model needs a bit of setup of the register model object object and it's callbacks. I would probably make a test class to share this over multiple tests if I was doing this for real
- The register model aims to remove register addresses, field masking operations and endianness from code. So the function deal in integer types.

Please let me know if you have more questions.

**Comment by jahagirdar** [comment]
Thanks for the code.
I had to make some changes to the read call back because the code above gave the following error
```
 return await int.from_bytes(axi.read(addr, 4), byteorder='big', signed=False)
 TypeError: cannot convert 'coroutine' object to bytes
```
I changed it to
```
      async def read_callback(addr: int, width: int, accesswidth: int) -> int:
         """ 
         32-bit read operation to the register model
         """
         rdata = await axi.read(addr, 4)
         b = int.from_bytes(rdata.data, byteorder='big', signed=False)
         cocotb.log.info(f"{rdata.data}, {hex(b)}")
         return b
```
This gets used as
```
   rdata = await dut_reg_model.GPIO_OE.gpio_oe.read()  # field read
   cocotb.log.info(rdata)
```
While the info statement in the callback prints the proper value, the info statement in the Frontdoor check prints 0 as the value. Am I missing something?
```
    31.00ns INFO     cocotb                             b'\xff\x03\x00\x00', 0xff030000
    31.00ns INFO     cocotb                             0
    31.00ns INFO     cocotb.regression                  test failed
```

**Comment by krcb197** [comment]
I will take a look, I suspect there is an `await` statement missing somewhere so it skips forward.

**Comment by krcb197** [comment]
@jahagirdar 

I have found the problem, the following line of code reads the field (not the whole register)
```python
rdata = await dut_reg_model.GPIO_OE.gpio_oe.read()  # field read
```
The field in the register is defined as using bits[9:0]. 0xFF03000000 bitwise anded with 0x3FF is 0 so this behaviour is correct. 

I suspect the cause of the issue is the endianness, in the example I provided the conversion from bytes to it using a big endian assumption. I should have looked harder at your example because I suspect your example is little endian.

for example
```python
int.from_bytes(b'\xff\x03\x00\x00', byteorder='little', signed=False)
```
returns `0x3FF` which in turn would have worked correctly in your example. 

If you swap the `byteorder` parameters from `big` to `little` in the callbacks I think you might have more success. 

Let me know how it turns out.

**Comment by jahagirdar** [comment]
Thanks, that worked.
I am attaching the updated test.py file for reference.
[test.py.gz](https://github.com/krcb197/PeakRDL-python/files/14002132/test.py.gz)

**Pull request merged**
