### PR TITLE
Issue #47 - add child getter generators to addrmap/regfile classes

### PR DESCRIPTION
**Pull request by mpriestleyidex**
This adds the generators discussed, with optional unrolling of array children.
It doesn't add any of the other niceties - I'll make separate tickets for those.

I'm aware that everything else is done as properties, but that prevents passing an `unroll` argument.

### CODE REVIEW

**Review by krcb197 — APPROVED** [review]
@mpriestleyidex these changes look fairly reasonable, I am putting them on a branch to allow some testing. I want to add test cases for these features before they go back to main

**Comment by krcb197** [comment]
There seems to be a problem with the test cases on main that needs to be fixed first before I can merge this. One of the test cases uses an IPXACT import that seems to have stopped working.

**Comment by mpriestleyidex** [comment]
I expect you've already worked this out, but the breaking change to the ipxact exporter comes from https://github.com/SystemRDL/PeakRDL-ipxact/releases/tag/v3.3.0 which means that in your test suite the IPXACT addressmap ``simple`` now gets imported as ``simple__simple_mmap__simple``.

We could:
- update to the new convention, and require `peakrdl-ipxact>=3.3.0`
- stick to the old one, and require `peakrdl-ipxact<3.3.0`
- detect the version of peakrdl-ipxact and do hideous name-munging magic

The first of these seems right to me. Should I make the change in this PR?

**Comment by krcb197** [comment]
> I expect you've already worked this out, but the breaking change to the ipxact exporter comes from https://github.com/SystemRDL/PeakRDL-ipxact/releases/tag/v3.3.0 which means that in your test suite the IPXACT addressmap `simple` now gets imported as `simple__simple_mmap__simple`.
> 
> We could:
> 
> * update to the new convention, and require `peakrdl-ipxact>=3.3.0`
> * stick to the old one, and require `peakrdl-ipxact<3.3.0`
> * detect the version of peakrdl-ipxact and do hideous name-munging magic
> 
> The first of these seems right to me. Should I make the change in this PR?

You have beaten me to getting that problem understood, I will make a bug fix branch from main and fix that later today. Thank you for your help.

**Pull request merged**
