### PR TITLE
Async enhancement merge

### PR DESCRIPTION
**Pull request by krcb197**
Added the async access register model

### CODE REVIEW

**Comment by krcb197** [comment]
@apstrike

I ran the pylint and mypy static checks over this code, it is shows some areas which I need you help to review:
```
src\peakrdl_python\templates\peakrdl_python\callbacks.py:58:8: E0302: The special method '__await__' expects 0 param(s), 3 were given (unexpected-special-method-signature)
src\peakrdl_python\templates\peakrdl_python\callbacks.py:67:8: E0302: The special method '__await__' expects 0 param(s), 4 were given (unexpected-special-method-signature)
src\peakrdl_python\templates\peakrdl_python\callbacks.py:76:8: E0302: The special method '__await__' expects 0 param(s), 4 were given (unexpected-special-method-signature)
src\peakrdl_python\templates\peakrdl_python\callbacks.py:85:8: E0302: The special method '__await__' expects 0 param(s), 4 were given (unexpected-special-method-signature)
```

```
>mypy src/peakrdl_python --config-file=tests/.mypy.ini
src\peakrdl_python\templates\peakrdl_python\memory.py:310: error: Return type "Coroutine[Any, Any, array[Any]]" of "read" incompatible with return type "array[Any]" in supertype "MemoryReadOnly"
src\peakrdl_python\templates\peakrdl_python\memory.py:375: error: Return type "Coroutine[Any, Any, None]" of "write" incompatible with return type "None" in supertype "MemoryWriteOnly"
src\peakrdl_python\templates\peakrdl_python\register.py:360: error: Return type "Coroutine[Any, Any, int]" of "read" incompatible with return type "int" in supertype "RegReadOnly"
src\peakrdl_python\templates\peakrdl_python\register.py:395: error: Return type "Coroutine[Any, Any, None]" of "write" incompatible with return type "None" in supertype "RegWriteOnly"
src\peakrdl_python\templates\peakrdl_python\register.py:430: error: Return type "Coroutine[Any, Any, None]" of "write_fields" incompatible with return type "None" in supertype "RegWriteOnly"
src\peakrdl_python\templates\peakrdl_python\register.py:489: error: Signature of "write" incompatible with supertype "RegWriteOnly"
src\peakrdl_python\templates\peakrdl_python\register.py:516: error: Return type "Coroutine[Any, Any, int]" of "read" incompatible with return type "int" in supertype "RegReadOnly"
src\peakrdl_python\templates\peakrdl_python\register.py:533: error: Return type "Coroutine[Any, Any, None]" of "write_fields" incompatible with return type "None" in supertype "RegWriteOnly"
src\peakrdl_python\templates\peakrdl_python\fields.py:603: error: Return type "Coroutine[Any, Any, int]" of "read" incompatible with return type "int" in supertype "FieldReadOnly"
src\peakrdl_python\templates\peakrdl_python\fields.py:654: error: Return type "Coroutine[Any, Any, None]" of "write" incompatible with return type "None" in supertype "FieldWriteOnly"
src\peakrdl_python\templates\peakrdl_python\fields.py:699: error: "write" of "RegWriteOnly" does not return a value
src\peakrdl_python\templates\peakrdl_python\fields.py:790: error: Definition of "parent_register" in base class "FieldAsyncReadOnly" is incompatible with definition in base class "FieldAsyncWriteOnly"
src\peakrdl_python\templates\peakrdl_python\fields.py:790: error: Definition of "parent_register" in base class "FieldAsyncReadOnly" is incompatible with definition in base class "FieldWriteOnly"
src\peakrdl_python\templates\peakrdl_python\fields.py:790: error: Definition of "parent_register" in base class "FieldReadOnly" is incompatible with definition in base class "FieldAsyncWriteOnly"
src\peakrdl_python\templates\peakrdl_python\fields.py:790: error: Definition of "parent_register" in base class "FieldReadOnly" is incompatible with definition in base class "FieldWriteOnly"
```

**Comment by krcb197** [comment]
@apstrike

I also had trouble with python 3.11 as that was throwing lots of errors relating to asynctest. I think this is the issue you eluded to on the previous PR with python 3.7. If I understand correctly the solution is to only use aynctest in python 3.7 and in all other versions use the native unittest functionality. So I have put in a change to only use asynctest in python 3.7 and it seems to be working OK.

**Comment by krcb197** [comment]
@apstirke

Even though all the test are passing, there are a large number of warnings in the form:
```
testcase_output/autopep8_async/addr_map/tests/test_addr_map.py::addr_map_TestCase::test_register_read_fields
  /opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/unittest/case.py:678: DeprecationWarning: It is deprecated to return a value that is not None from a test case (<bound method addr_map_TestCase.test_register_read_fields of <autopep8_async.addr_map.tests.test_addr_map.addr_map_TestCase testMethod=test_register_read_fields>>)
    return self.run(*args, **kwds)

testcase_output/autopep8_async/addr_map/tests/test_addr_map.py::addr_map_TestCase::test_register_write_context_manager
testcase_output/raw_async/addr_map/tests/test_addr_map.py::addr_map_TestCase::test_register_write_context_manager
  /opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/unittest/case.py:579: RuntimeWarning: coroutine 'addr_map_TestCase.test_register_write_context_manager' was never awaited
    if method() is not None:
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.
```

I think you mentioned this in you earlier PR, can you take a look?

**Comment by apstrike** [comment]
@krcb197 sorry about all the trouble. I only have access to Python 3.7 and so I'm not able to test out any other python versions. 
To clarify, the asyntest library was used specifically to have the async tests be compatible with Python 3.7, sorry that wasn't clear. I thought that it was compatible with future versions of Python as well but it seems I was wrong about that.

**Comment by krcb197** [comment]
@apstrike, this is no trouble the aim of an open source software is engaging with other people to make a better solution for the all users. You have made a valuable contribution that I hadn't thought of myself, which also forced me to extend my personal python knowledge and I look forward to further collaboration with you. It would be much worse to publish an open source project and never get any feedback or contributions.

I think the issues with different versions of python are now largely resolved. Together we need to resolve the outstanding issues:
- Need to update the documentation for this feature
- Need to resolve the outstanding typing checks errors (which are tested with mypy) 
- Need to resolve the warning related to the context manager 

You should be able to run the GitHub CI action from the web interface to see all the errors and warnings from all versions of python 3.7, 3.8, 3.9, 3.10 and 3.11.

**Comment by krcb197** [comment]
I suspected as much, this is likely to be a case where it would be acceptable to suppress the typing check to stock the error. However, as the async function is still new to me, I didn't want to just hide the problem without reviewing it with you.

**Comment by apstrike** [comment]
Seeing as how we never use the Async and non-Async functions together, I'd think that it should fine to suppress the errors (though I'll admit I'm not sure how that's done). Either way, Python gives out a RuntimeWarning if an async function is called (which generates a coroutine) but never awaited & so a user would be made aware in that case that they were using the async function version

**Comment by krcb197** [comment]
The mypy errors are suppressed with a the `# type` directive. I am more concerned by the runtime warning. I would prefer to avoid users routinely being presented with warnings, I think we need address that issue.

**Comment by apstrike** [comment]
I'm not sure something can be done to prevent that, to clarify if a user were to use the async version of the library and run something like:
```
my_register.read() # This returns a coroutine that can be awaited 
``` 
They will receive a runtime warning that the coroutine generated was never awaited. This warning is usually a good thing and implies an error in the usage of the read function. This will only occur in this situation. based on the library, if a user used the non-async version of the library then they will never see this. The correct usage of the API is one of:
```
await my_register.read()
```
or 
``` 
f = my_register.read()
...
await f
```

**Comment by krcb197** [comment]
I think I have been able to address the issues with the warnings by use of the `unittest.IsolatedAsyncioTestCase` for the unittests that removes all the warnings, I have managed to clear down a lot of the pylint and typing errors in the library itself, next step is all the generated code.

**Comment by krcb197** [comment]
Thank you @apstrike for the original hard work to make this feature work

**Comment by apstrike** [comment]
thanks @krcb197 for all the work integrating the changes into the project. One small possible typo I think I may have noticed is that the async callback set class is named `AysncCallbackSet` rather than `AsyncCallbackSet` (the y and s are swapped in Async)

**Comment by krcb197** [comment]
@apstrike That is a good spot. I have yanked the 0.4.0 release and replaced it with a 0.4.1 release with the name corrected. Thank you again for your contribution to this project.

**Pull request merged**
